Repository DES-Terminal/DES-Explorer, pull requests merged in 2022-07, with the labels that each got.

#1 메인 클래스 기본적 기능 작성
  include/DES_Explorer.hpp
  include/Logger.hpp
  src/DES_Explorer.cpp
  src/main.cpp
Labels: enhancement, good first issue

#2 Cmake 파일 작성 및 적용
  .gitignore
  CmakeLists.txt
  includes/DES_Explorer.hpp
  includes/Logger.hpp
  src/DES_Explorer/DES_Explorer.cpp
  src/main.cpp
Labels: enhancement

#4 특정 위치부터 파일을 읽어오는 함수 작성
  includes/utils/FileReader.hpp
  includes/utils/Logger.hpp
  src/DES_Explorer/utils/FileReader.cpp
Labels: enhancement

#5 코드 스타일 통합 및 일부 오류 해결
  CMakeLists.txt
  includes/DES_Explorer.hpp
  includes/Logger.hpp
  includes/utils/FileReader.hpp
  src/DES_Explorer/DES_Explorer.cpp
  src/DES_Explorer/utils/FileReader.cpp
Labels: enhancement, invalid
